exclude_dirs:
  - venv
  - .venv
  - backups
  - node_modules
  - "**/site-packages"
  - "**/.tox"
  - "**/.mypy_cache"
  - "**/.pytest_cache"
severity: MEDIUM
confidence: HIGH
skips:
  - B404
  - B603
  - B607
  - B311
  - B112
  - B110
